# Shell configuration abbreviations.
abbr efa "code ~/.config/fish/conf.d"
abbr efc "code ~/.config/fish/config.fish"
abbr eff "code ~/.config/fish/functions"

# System abbreviations.
abbr ff "fastfetch"

# Terminal tools abbreviations.
abbr cat "bat"
abbr ls "eza --long --all --icons --color=always --group-directories-first --git"
abbr cp "cp_to_xcp"
abbr eva "calc"
abbr cd "z"
abbr cl "clear"
abbr find "fd"
abbr sed "sd"
abbr mkdir "mkdir -p"
abbr jsn "jless"
abbr hlx "helix"
abbr h "atuin history list"
abbr hs "atuin search -i"
abbr cl "clear"
abbr rmdp "keep_best_file | xargs rm -v"
abbr dl "aria2c -x 10 "
abbr st "gg"

# `Git` abbreviations.
abbr egc "code ~/.gitconfig"
abbr g "git"
abbr gl "git log"
abbr gls "git_log_current_branch"
abbr gpl "git pull"
abbr gft "git fetch"
abbr gftpl "git fetch && git pull"
abbr gps "git push"
abbr gpsf "git push -f"
abbr ga "git add"
abbr gap "git add -p"
abbr gc "git commit"
abbr gca "git commit --amend"
abbr gcp "git cherry-pick"
abbr gcpc "git_cherry_pick_commit"
abbr gcpa "git cherry-pick --abort"
abbr gst "git status"
abbr gd "git diff"
abbr gds "git diff --staged"
abbr gdsn "git diff --staged --name-only"
abbr gco "git checkout"
abbr gcob "git checkout -b"
abbr grstr "git restore"
abbr grstrs "git restore --staged"
abbr grstrss "git restore --staged -p"
abbr grstb "git fetch origin && git reset --hard origin/(git rev-parse --abbrev-ref HEAD)"
abbr grst1 "git reset HEAD~"
abbr grstlb "git reset --hard HEAD"
abbr gfrb "git_fetch_and_rebase"
abbr grb "git rebase -i --autosquash HEAD~"
abbr grba "git rebase --abort"
abbr grbc "git rebase --continue"
abbr grbs "git rebase --skip"
abbr gbr "git branch"
abbr gbrls "git_list_branches"
abbr gbrd "git branch -d"
abbr gbrdf "git branch -D"
abbr gbrr "git branch -m"
abbr gsts "git_stash"
abbr gstsl "git_stash_list"
abbr gstsa "git stash apply"
abbr gstsp "git stash pop"
abbr gstsd "git stash drop"
abbr gfx "git commit --fixup"
abbr gafx "git_auto_fix_up"
abbr grp "git prune && rm -rf ./.git/gc.log && git gc --prune now && git remote prune origin"
abbr gmr "git revert -m 1"
abbr grc "git revert"
abbr gm "git_merge_to_default_branch"
abbr gsu "git_add_remote_branch"

# `Docker` abbreviations.
abbr d "docker"

# `OS`-specific abbreviations.
set kernel_name (uname -s)
if test "$kernel_name" = "Darwin"
    source $HOME/.config/fish/conf.d/macos/abbr.fish
else
    source $HOME/.config/fish/conf.d/linux/abbr.fish
end
