# Shell configuration abbreviations.
abbr efa "code ~/.config/fish/conf.d/abbr.fish"
abbr efc "code ~/.config/fish/config.fish"
abbr eff "code ~/.config/fish/functions"

# System abbreviations.
abbr um "rate-mirrors --disable-comments-in-file --save mirrors.txt arch && cat mirrors.txt | head -n 5 | sudo tee /etc/pacman.d/mirrorlist && sudo rm mirrors.txt"
abbr us "sudo pacman-db-upgrade && sudo pacman -Sy && sudo pacman -S --noconfirm --needed archlinux-keyring && paru -Su --noconfirm"
abbr pi "paru -S --noconfirm --needed"
abbr pr "paru -Rns --noconfirm"
abbr ff "fastfetch"
abbr ip "ip -br a | grep UP | awk '{print \"Interface: \" \$1 \"\nIPv4: \" \$3}'"
abbr po "sudo systemctl poweroff"
abbr zzz "sudo systemctl suspend"

# Terminal tools abbreviations.
abbr cat "bat"
abbr ls "exa --long --all --icons --color=always --group-directories-first --git"
abbr cp "cp_to_xcp"
abbr t "trash"
abbr tl "trash list"
abbr te "trash_empty"
abbr tr "trash_restore"
abbr tea "trash empty --all"
abbr eva "calc"
abbr cd "z"
abbr cl "clear"
abbr find "fd"
abbr sed "sd"
abbr mkdir "mkdir -p"
abbr jsn "jless"
abbr hlx "helix"
abbr h "atuin history list"
abbr hs "atuin search -i"
abbr cl "clear"
abbr rmdp "keep_best_file | xargs rm -v"

# Services abbreviations.
abbr sc "sudo systemctl"
abbr scsts "sudo systemctl status"
abbr sci "sudo systemctl info"
abbr scstr "sudo systemctl start"
abbr sce "sudo systemctl enable"
abbr scstp "sudo systemctl stop"
abbr scd "sudo systemctl disable"
abbr scrr "sudo systemctl reload-or-restart"

# Git abbreviations.
abbr egc "code ~/.gitconfig"
abbr g "git"
abbr gl "git log"
abbr gls "git_log_current_branch"
abbr gpl "git pull"
abbr gft "git fetch"
abbr gftpl "git fetch && git pull"
abbr gps "git push"
abbr gpsf "git push -f"
abbr ga "git add"
abbr gap "git add -p"
abbr gc "git commit"
abbr gca "git commit --amend"
abbr gcp "git cherry-pick"
abbr gcpc "git_cherry_pick_commit"
abbr gcpa "git cherry-pick --abort"
abbr gst "git status"
abbr gd "git diff"
abbr gds "git diff --staged"
abbr gdsn "git diff --staged --name-only"
abbr gco "git checkout"
abbr gcob "git checkout -b"
abbr grstr "git restore"
abbr grstrs "git restore --staged"
abbr grstrss "git restore --staged -p"
abbr grstb "git fetch origin && git reset --hard origin/(git rev-parse --abbrev-ref HEAD)"
abbr grst1 "git reset HEAD~"
abbr grstlb "git reset --hard HEAD"
abbr gfrb "git_fetch_and_rebase"
abbr grb "git rebase -i --autosquash HEAD~"
abbr grba "git rebase --abort"
abbr grbc "git rebase --continue"
abbr grbs "git rebase --skip"
abbr gbr "git branch"
abbr gbrls "git_list_branches"
abbr gbrd "git branch -d"
abbr gbrdf "git branch -D"
abbr gbrr "git branch -m"
abbr gsts "git_stash"
abbr gstsl "git_stash_list"
abbr gstsa "git stash apply"
abbr gstsp "git stash pop"
abbr gstsd "git stash drop"
abbr gfx "git commit --fixup"
abbr gafx "git_auto_fix_up"
abbr grp "git prune && rm -rf ./.git/gc.log && git gc --prune now && git remote prune origin"
abbr gmr "git revert -m 1"
abbr grc "git revert"
abbr gm "git_merge_to_default_branch"

# Docker abbreviations.
abbr d "docker"
abbr dc "docker-compose"
abbr dcu "docker-compose up --build -d"
abbr dcd "docker-compose down"
abbr de "docker-compose exec --it /bin/bash"
abbr dcp "docker compose down -v --remove-orphans && echo y | docker system prune -a --volumes"
