# Enable anti-aliasing for fonts and components for better text rendering.
env = _JAVA_OPTIONS, -Dawt.useSystemAAFontSettings=on

# Tells the Clutter graphical library to use Wayland as the backend.
env = CLUTTER_BACKEND, wayland

# Instructs GDK to try using Wayland first, then fall back to x11 if Wayland is not available.
env = GDK_BACKEND, wayland, x11

# Enables automatic scaling for high-DPI screens in Qt applications.
env = QT_AUTO_SCREEN_SCALE_FACTOR, 1

# Specifies that Qt applications should try using the Wayland platform, and fall back to xcb (X11) if Wayland is not available.
env = QT_QPA_PLATFORM, wayland;xcb

# Sets the theme platform for Qt applications to "qt5ct", which allows for customization of Qt5 applications' look and feel.
env = QT_QPA_PLATFORMTHEME, qt5ct

# Sets the scaling factor for Qt applications; "1" implies normal scaling (no DPI scaling).
env = QT_SCALE_FACTOR, 1

# Disables client-side window decorations in Qt applications when running under Wayland.
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1

# Sets the name of the currently running desktop environment to "Hyprland" for applications that query this variable.
env = XDG_CURRENT_DESKTOP, Hyprland

# Identifies the name of the desktop session as "Hyprland" for use in desktop-aware applications and utilities.
env = XDG_SESSION_DESKTOP, Hyprland

# Sets the session type to "wayland" indicating that the current session is running under the Wayland protocol.
env = XDG_SESSION_TYPE, wayland

# Set cursor size.
env = XCURSOR_SIZE, 24

# Enable Wayland support for Mozilla software.
env = MOZ_ENABLE_WAYLAND, 1
