# Instructing Qt applications to run on the Wayland platform rather than X11.
env = QT_QPA_PLATFORM, wayland

# Enable anti-aliasing for fonts and components for better text rendering.
env = _JAVA_OPTIONS, -Dawt.useSystemAAFontSettings=on

# Set cursor size.
env = XCURSOR_SIZE, 24
