# Loads environment variable configurations.
source = ~/.config/hypr/environment_variables.conf

# Loads configuration for input devices.
source = ~/.config/hypr/input_devices.conf

# Loads monitor/display settings for the session.
source = ~/.config/hypr/monitors.conf

# Loads key bindings for window management and other actions.
source = ~/.config/hypr/key_bindings.conf

# Loads general Hyprland settings such as window gaps, animations, etc.
source = ~/.config/hypr/settings.conf

# Loads theming configuration for Hyprland, like colors and border widths.
source = ~/.config/hypr/theme.conf

# Loads window rules for Hyprland configuration.
source = ~/.config/hypr/window_rules.conf

# Loads autostart configurations and programs.
source = ~/.config/hypr/autostart.conf
