input {

    # US and GR keyboard layout.
    kb_layout = us, gr

    # TODO: Add an option to change keyboard layout with main mod + space too.
    # Change keyboard layout via using ALT + SHIFT.
    kb_options = grp:alt_shift_toggle

    # Cursor movement affect window focus.
    follow_mouse = 1

    # No modification in sensitivity.
    sensitivity = 0

    # Empty keyboard variant, model and rules.
    kb_variant =
    kb_model =
    kb_rules =

    # Touchpad options.
    touchpad {

        # Handle scrolling moves as scrollbar.
        natural_scroll = false

        # Disable the touchpad while typing.
        disable_while_typing=true

        # Button presses with 1, 2, or 3 fingers will not be mapped to LMB, RMB, and MMB respectively.
        clickfinger_behavior=false

        # Sending LMB and RMB simultaneously will be interpreted as a middle click.
        middle_button_emulation=true

        # Tapping on the touchpad with 1, 2, or 3 fingers will send LMB, RMB, and MMB respectively.
        tap-to-click=true

        # Lifting the finger off for a short time while dragging will drop the dragged item.
        drag_lock=false
    }
}
