input {

    # US and GR keyboard layout.
    kb_layout = us, gr

    # TODO: Add an option to change keyboard layout with main mod + space too.
    # Change keyboard layout via using ALT + SHIFT.
    kb_options = grp:alt_shift_toggle

    # TODO: Check if we can omit all the below options, for being either empty or using the default values.
    # Handle scrolling moves as scrollbar.
    touchpad {
        natural_scroll = no
    }

    # Cursor movement affect window focus.
    follow_mouse = 1

    # No modification in sensitivity.
    sensitivity = 0

    # Empty keyboard variant, model and rules.
    kb_variant =
    kb_model =
    kb_rules =
}
