# Automatic detection of monitors.
monitor-autodetect = true

# Automatically assign workspaces to monitors when they are connected.
monitor-workspace-assignment = true

# Configure monitors automatically.
monitor=,preferred,auto,auto
