# Base configuration.
command_timeout = 10000
add_newline = true

# Command duration.
[cmd_duration]
min_time = 4
show_milliseconds = false
format = "| 🕙$duration "
style = "bold italic #87A752"

# Directory.
[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "bold cyan"

# Hostname.
[hostname]
ssh_only = false
format = "<$hostname>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

# Character.
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✖](bold red) "

# Username.
[username]
show_always = false
style_user = "bold dimmed blue"
style_root = "bold dimmed red"

# Packages.
[package]
disabled = false

# Memory.
[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

# Background jobs.
[jobs]
format = "[$symbol$jobs]($style) "
symbol = "🔃 "
style = "bold blue"

# Git.
[git_branch]
format = "on [$symbol$branch]($style) "
symbol = ""
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "⚔️ "
ahead = "🏎️×${count} "
behind = "🐢×${count} "
diverged = "🏎️×${ahead_count} 🐢×${behind_count} "
untracked = "🛤️×${count} "
stashed = "📦 "
modified = "📝×${count} "
staged = "🗃️×${count} "
renamed = "📛×${count} "
deleted = "🗑️×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

# Languages & Tools.
[nodejs]
format = "⬢$version "
style = "bold green"

[rust]
format = "🦀$version "
style = "bold red"

[python]
format = "🐍$version "
style = "bold blue"

[golang]
format = "🐹$version "
style = "bold cyan"

[java]
format = "☕$version "
style = "bold purple"

[kubernetes]
format = "☸️$context "
style = "bold blue"

[docker_context]
format = "🐳$context "
style = "blue bold"

[c]
format = "⚙️$version "
style = "bold orange"

[dotnet]
format = "☁️$version "
style = "bold blue"

[dart]
format = "🎯$version "
style = "bold cyan"

[ruby]
format = "💎$version "
style = "bold red"
