# Set main mod constant variable.
main_mod = SUPER

# Kill active window.
bind = $main_mod, Q, killactive

# Exit.
bind = $main_mod SHIFT, Q, exit

# Launch WezTerm terminal emulator.
bind = $main_mod, T, exec, wezterm

# Launch Rofi application launcher.
bind = $main_mod, R, exec, pkill rofi || rofi -show drun -modi run, drun, filebrowser

# Launch Dolphin file explorer.
bind = $main_mod, E, exec, dolphin

# Launch Spacedrive file explorer.
bind = $main_mod SHIFT, E, exec, spacedrive

# Launch Notepadqq text editor.
bind = $main_mod, N, exec, notepadqq

# Cycle through active windows and bringing the on top.
bind = ALT, Tab, cyclenext
bind = ALT, Tab, bringactivetotop

# Toggle floating.
bind = $main_mod, V, togglefloating

# Activate pseudo-tiling mode
bind = $main_mod, P, pseudo

# Activate pseudo-full screen mode.
bind = SUPER, H, fakefullscreen

# Togle split.
bind = $main_mod, J, togglesplit

# Set window in full screen mode.
bind = $main_mod, F, fullscreen, 1

# Exit from full screen mode.
bind = $main_mod SHIFT, F, fullscreen, 0

# TODO: Create screenshots directory if not exists.
# Screenshot a window, using hyprshot package.
bind = $main_mod SHIFT, P, exec, hyprshot -m window -o $HOME/Pictures/Screenshots

# Screenshot a monitor, using hyprshot package.
bind = $main_mod CTRL, P, exec, hyprshot -m output -o $HOME/Pictures/Screenshots

# Screenshot a region, using hyprshot package.
bind = $main_mod ALT, P, exec, hyprshot -m region -o $HOME/Pictures/Screenshots

# TODO: Add specific key bindings in case the defined buttons do not exist.
# Media controls for pausing, playing previous/nect track, using playerctl package.
bind = ,XF86AudioPrev, exec, playerctl previous
bind = ,XF86AudioPlay, exec, playerctl play-pause
bind = ,XF86AudioNext, exec, playerctl next

# TODO: Add specific key bindings in case the defined buttons do not exist.
# Volume controls.
bind = ,XF86AudioMute, exec, volume --toggle
bind = ,XF86AudioLowerVolume, exec, volume --down
bind = ,XF86AudioRaiseVolume, exec, volume --up

# Move focus with main_mod + arrow keys.
bind = $main_mod, left, movefocus, l
bind = $main_mod, right, movefocus, r
bind = $main_mod, up, movefocus, u
bind = $main_mod, down, movefocus, d

# Go to previous workspace.
bind = $main_mod, Tab, workspace, previous

# Switch workspaces with main_mod + [1-6].
bind = $main_mod, 1, workspace, 1
bind = $main_mod, 2, workspace, 2
bind = $main_mod, 3, workspace, 3
bind = $main_mod, 4, workspace, 4
bind = $main_mod, 5, workspace, 5
bind = $main_mod, 6, workspace, 6

# Move active window to a workspace with main_mod + SHIFT + [1-6].
bind = $main_mod SHIFT, 1, movetoworkspace, 1
bind = $main_mod SHIFT, 2, movetoworkspace, 2
bind = $main_mod SHIFT, 3, movetoworkspace, 3
bind = $main_mod SHIFT, 4, movetoworkspace, 4
bind = $main_mod SHIFT, 5, movetoworkspace, 5
bind = $main_mod SHIFT, 6, movetoworkspace, 6

# Scroll through existing workspaces with main_mod + scroll.
bind = $main_mod, mouse_down, workspace, e+1
bind = $main_mod, mouse_up, workspace, e-1

# Move/resize windows with main_mod + LMB/RMB and dragging.
bindm = $main_mod, mouse:272, movewindow
bindm = $main_mod, mouse:273, resizewindow

# Move windows with keyboard.
bind = $main_mod SHIFT, left, movewindow, l
bind = $main_mod SHIFT, right, movewindow, r
bind = $main_mod SHIFT, up, movewindow, u
bind = $main_mod SHIFT, down, movewindow, d

# Resize windows with keyboard.
bind = $main_mod CTRL, left, resizeactive, -50 0
bind = $main_mod CTRL, right, resizeactive, 50 0
