# "dwindle" layout organizes windows in a binary tree structure.
dwindle {

  # Pseudotiling keeps windows at their floating size when tiled.
  pseudotile = true

  # Preserve original window split direction despite layout changes.
  preserve_split = true
}

# "master" layout features a primary window(s) on the workspace.
master {

  # New windows become the main focus in the master layout.
  new_is_master = true
}

# Configuration for input gestures.
gestures {

  # Disables switching workspaces with a swipe gesture.
  workspace_swipe = false
}

# Bindings settings for workspace navigation.
binds {

  # Toggle between current and previous workspace.
  allow_workspace_cycles = true
}

# Miscellaneous settings for appearance and performance.
misc {

  # Hide the default Hyprland background logo.
  disable_hyprland_logo = true

  # Turn off splash screen animations on load.
  disable_splash_rendering = true

  # Disable animations for manual window resizes and moves.
  animate_manual_resizes = false

  # Disable animations when dragging windows with the mouse.
  animate_mouse_windowdragging = false

  # Enable Variable Frame Rate (VFR) support.
  vfr = true

  # Set Variable Refresh Rate (VRR) settings (0 - off, 1 - on, 2 - fullscreen only).
  vrr = 2

  # Wake monitors on mouse movement with DPMS off.
  mouse_move_enables_dpms = true

  # Enable terminal window swallowing for spawned applications.
  enable_swallow = true

  # Disable direct scanout for fullscreen applications.
  no_direct_scanout = true

  # Focus apps that request to be focused.
  focus_on_activate = true
}
