# Delays execution for 1 second, then updates the systemd user environment with the current Wayland display and desktop variables.
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Starts the xdg-desktop-portal-Hyprland service for the current user, which allows sandboxed apps to use Hyprland-specific features.
exec-once = systemctl --user start xdg-desktop-portal-hyprland

# Watches the clipboard for new text entries and stores them in a clipboard history manager without adding new lines.
exec-once = wl-paste --type text --watch cliphist store --no-newline

# Watches the clipboard for new image entries and stores them in a clipboard history manager.
exec-once = wl-paste --type image --watch cliphist store

# Executes the script to import GTK settings, to ensure consistent theming across applications.
exec-once = $XDG_CONFIG_HOME/gtk-3.0/import_gtk_settings.sh
