# General settings control layout and window interaction.
general {
  
  # Set inner window-to-screen edge gap.
  gaps_in = 10

  # Set outer window-to-window gap.
  gaps_out = 30

  # Define border thickness for windows.
  border_size = 4

  # Active window border color.
  col.active_border = rgb(303030)

  # Inactive window border color.
  col.inactive_border = rgb(191919)

  # Disable window resize from border dragging.
  resize_on_border = false

  # Maintain default border click detection area.
  extend_border_grab_area = false

  # Show icon when hovering over window borders.
  hover_icon_on_border = true

  # Default layout for new workspaces.
  layout = dwindle
}

# Decoration settings improve visual window appeal.
decoration {

  # Radius for window corner rounding.
  rounding = 15

  # Apply anti-aliasing to window edges.
  multisample_edges = true

  # Turn on window shadow effect.
  drop_shadow = true

  # Set shadow size and intensity.
  shadow_range = 16
  shadow_render_power = 4

  # Exclude certain windows from shadow effect.
  shadow_ignore_window = true

  # Shadow color.
  col.shadow = rgb(000000)

  # Configure blur effect for window transparency.
  blur {

    # Enable blur effect.
    enabled = yes

    # Blur radius.
    size = 8

    # Number of blur effect iterations.
    passes = 2

    # Enable optimizations for blur.
    new_optimizations = on
  }
}

# Animation settings add dynamics to UI elements.
animations {

    # Enable animations for visual effects.
    enabled = yes

    # Set bezier curve for animation timing.
    bezier = quart, 0.25, 1, 0.5, 1

    # Window animation configuration.
    animation = windows, 1, 6, quart, slide

    # Window border animation configuration.
    animation = border, 1, 6, quart

    # Window border angle animation configuration.
    animation = borderangle, 1, 6, quart

    # Fade effect animation configuration.
    animation = fade, 1, 6, quart

    # Workspace switch animation configuration.
    animation = workspaces, 1, 6, quart
}
